[build]
  command = "npm run build"
  functions = "functions"
  publish = "_site"

[functions."scheduled-deploys"]
schedule = "0 14 * * *"

# =[ NEWSLETTER ] =====================
# reset email flag on fauna
#[functions."newsletter-isSent-false"]
#schedule = "*/20 16 * * *"
# --------------------------------------
# each worker can send 500 messages
[functions."newsletter-send"]
schedule = "30,0 06-18 * * *"
# --------------------------------------

###[functions."newsletter-send-0001-0500"]
###schedule = "00 06 * * *"
###
###[functions."newsletter-send-0500-1000"]
###schedule = "30 06 * * *"
###
###[functions."newsletter-send-1000-1500"]
###schedule = "00 07 * * *"
###
###[functions."newsletter-send-1500-2000"]
###schedule = "30 07 * * *"
# --------------------------------------
