[build]
  command = "npm run build"
  functions = "functions"
  publish = "_site"

[functions."scheduled-deploys"]
schedule = "00 14 * * *"

[functions."test-worker-1"]
schedule = "* * * * *"
#schedule = "58 9 24 feb *"

